import dayjs from 'dayjs';

export const data = [
    {
      id: '1',
      calendarId: '123',
      recurrenceId: '0',
      title: '哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
      start: dayjs().minute(0).second(0).unix(),
      end: dayjs().add(1, 'day').minute(0).second(0).unix(),
      isAllDay: true,
      location: 'hshdh',
      attendees: [],
      isReadOnly: false,
      color: '#000',
      bgColor: 'skyblue',
      borderColor: '#00a9ff',
      customStyle: '',
      state: '1',
      raw: {},
    },
    // {
    //   id: '1',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: '哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
    //   start: dayjs().minute(0).second(0).unix(),
    //   end: dayjs().add(1, 'hour').minute(0).second(0).unix(),
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
    // {
    //   id: '1',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: '哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
    //   start: dayjs().minute(0).second(0).unix(),
    //   end: dayjs().add(1, 'hour').minute(0).second(0).unix(),
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
    // {
    //   id: '1',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: '哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
    //   start: dayjs().minute(0).second(0).unix(),
    //   end: dayjs().add(1, 'hour').minute(0).second(0).unix(),
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
    // {
    //   id: '2',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: 'hshhshsh',
    //   start: 1588606200,
    //   end: 1588608000,
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
    // {
    //   id: '2-2',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: '很快开始2',
    //   start: 1588075200,
    //   end: 1588078800,
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
    // {
    //   id: '2-3',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: '很快开始2',
    //   start: 1588075200,
    //   end: 1588078800,
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
    // {
    //   id: '3',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: '当说的是',
    //   start: 1587398400,
    //   end: 1587484800,
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
    // {
    //   id: '4',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: '视觉还原',
    //   start: 1587434400,
    //   end: 1587438000,
    //   isAllDay: false,
    //   location: '百度科技园',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
    {
      id: '5',
      calendarId: '123',
      recurrenceId: '0',
      title: '夸天1',
      start: dayjs().startOf('day').add(8, 'hour').unix(),
      end: dayjs().endOf('day').subtract(2, 'hour').unix(),
      isAllDay: false,
      location: 'hshdh',
      attendees: [],
      isReadOnly: false,
      color: '#000',
      bgColor: 'skyblue',
      borderColor: '#00a9ff',
      customStyle: '',
      state: '1',
      raw: {},
    },
    {
      id: '6',
      calendarId: '123',
      recurrenceId: '0',
      title: '夸天2',
      start: dayjs().startOf('day').add(1, 'hour').unix(),
      end: dayjs().endOf('day').add(3, 'day').unix(),
      isAllDay: false,
      location: 'hshdh',
      attendees: [],
      isReadOnly: false,
      color: '#000',
      bgColor: 'skyblue',
      borderColor: '#00a9ff',
      customStyle: '',
      state: '1',
      raw: {},
    },
    {
      id: '7',
      calendarId: '123',
      recurrenceId: '0',
      title: '夸天3',
      start: dayjs().startOf('day').add(0, 'day').unix(),
      end: dayjs().endOf('day').add(3, 'day').unix(),
      isAllDay: false,
      location: 'hshdh',
      attendees: [],
      isReadOnly: false,
      color: '#000',
      bgColor: 'skyblue',
      borderColor: '#00a9ff',
      customStyle: '',
      state: '1',
      raw: {},
    },
    {
      id: '8',
      calendarId: '123',
      recurrenceId: '0',
      title: '夸天4',
      start: dayjs().startOf('day').add(1, 'day').unix(),
      end: dayjs().endOf('day').add(3, 'day').unix(),
      isAllDay: false,
      location: 'hshdh',
      attendees: [],
      isReadOnly: false,
      color: '#000',
      bgColor: 'skyblue',
      borderColor: '#00a9ff',
      customStyle: '',
      state: '1',
      raw: {},
    },
    {
      id: '9',
      calendarId: '123',
      recurrenceId: '0',
      title: '当说的是1',
      start: dayjs().startOf('day').add(8, 'day').unix(),
      end: dayjs().endOf('day').add(12, 'day').unix(),
      isAllDay: false,
      location: 'hshdh',
      attendees: [],
      isReadOnly: false,
      color: '#000',
      bgColor: 'skyblue',
      borderColor: '#00a9ff',
      customStyle: '',
      state: '1',
      raw: {},
    },
    // {
    //   id: '10',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: '当说的是1',
    //   start: dayjs().startOf('day').unix(),
    //   end: dayjs().endOf('day').add(1, 'second').unix(),
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
    // {
    //   id: '11',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: '当说的是1',
    //   start: dayjs().startOf('day').unix(),
    //   end: dayjs().endOf('day').add(1, 'second').unix(),
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },

    // {
    //   id: '5',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: '当说的是2',
    //   start: dayjs().startOf('day').unix(),
    //   end: dayjs().endOf('day').add(1, 'second').unix(),
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
    // {
    //   id: '5',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: '当说的是3',
    //   start: dayjs().startOf('day').unix(),
    //   end: dayjs().endOf('day').add(1, 'second').unix(),
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
    // {
    //   id: '5',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: '当说的是4',
    //   start: dayjs().startOf('day').unix(),
    //   end: dayjs().endOf('day').add(1, 'second').unix(),
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
    // {
    //   id: '5',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: '当说的是5',
    //   start: dayjs().startOf('day').unix(),
    //   end: dayjs().endOf('day').add(1, 'day').unix(),
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
    // {
    //   id: '6',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: 'week全天',
    //   start: 1588608000,
    //   end: 1588694400,
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
    // {
    //   id: '6',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: 'week全天1',
    //   start: 1588608000,
    //   end: 1588694400,
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
    // {
    //   id: '6',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: 'week全天2',
    //   start: 1588608000,
    //   end: 1588694400,
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
    // {
    //   id: '6',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: 'week全天3',
    //   start: 1588608000,
    //   end: 1588694400,
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
    // {
    //   id: '6',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: 'month 1',
    //   start: dayjs().add(1,'day').startOf('day').unix(),
    //   end: dayjs().add(2,'day').startOf('day').unix(),
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
    // {
    //   id: '7',
    //   calendarId: '123',
    //   recurrenceId: '0',
    //   title: 'month 2',
    //   start: dayjs().add(3,'day').startOf('day').unix(),
    //   end: dayjs().add(4,'day').startOf('day').unix(),
    //   isAllDay: false,
    //   location: 'hshdh',
    //   attendees: [],
    //   isReadOnly: false,
    //   color: '#000',
    //   bgColor: 'skyblue',
    //   borderColor: '#00a9ff',
    //   customStyle: '',
    //   state: '1',
    //   raw: {},
    // },
  ]